### ISSUE TITLE
Question regarding photos and videos

### ISSUE THREAD

**Issue by AntonEvmenenko** [alextreseder/picoEDM#1]
Hi @alextreseder,

I just came across your EDM projects. Great job, they are really cool, thanks for open sourcing the designs!

My question is, do you have any photos/videos of the actual prototypes? If so, pls let me know where to find them.

**Comment by alextreseder** [comment]
Hello,

Im glad you like it!

You can join the discord channel for updates here.

https://discord.gg/8btrYmpe

Once i get the machine running stable, I’ll make some nice youtube videos
about it

Alex
